"use strict";(function(){
const BSC='0x38';
const short=a=>a.slice(0,8)+'…'+a.slice(-6);
function getSb(){return window.Web3MarketSupabase?.getClient?.()||window.supabaseClient||window.web3marketSupabase}
function init(){const sb=getSb(),card=document.querySelector('.wallet-card');if(!card||!sb||card.dataset.walletReady)return;const link=card.querySelector('.btn.full');if(!link)return;card.dataset.walletReady='1';link.textContent='Connect BNB Wallet';link.href='#';link.addEventListener('click',async e=>{e.preventDefault();const old=link.textContent;try{if(!window.ethereum)throw new Error('No compatible EVM wallet detected. Install MetaMask, Trust Wallet, or another EVM wallet.');link.textContent='Opening wallet…';link.style.pointerEvents='none';const accounts=await window.ethereum.request({method:'eth_requestAccounts'});const address=accounts?.[0];if(!address)throw new Error('No wallet account returned.');let chain=await window.ethereum.request({method:'eth_chainId'});if(chain!==BSC){try{await window.ethereum.request({method:'wallet_switchEthereumChain',params:[{chainId:BSC}]})}catch(err){if(err.code===4902){await window.ethereum.request({method:'wallet_addEthereumChain',params:[{chainId:BSC,chainName:'BNB Smart Chain',nativeCurrency:{name:'BNB',symbol:'BNB',decimals:18},rpcUrls:['https://bsc-dataseed.binance.org/'],blockExplorerUrls:['https://bscscan.com/']}]})}else throw err;}}
const {data:{user},error:ue}=await sb.auth.getUser();if(ue||!user)throw new Error('Buyer session expired. Please sign in again.');
const message=`Web3Market Buyer Wallet Verification\n\nI am connecting this wallet to my Web3Market buyer account.\n\nWallet: ${address}\nChain: BNB Smart Chain\nTimestamp: ${new Date().toISOString()}\n\nThis signature does not authorize any transaction or transfer of funds.`;
link.textContent='Sign in wallet…';const signature=await window.ethereum.request({method:'personal_sign',params:[message,address]});if(!signature)throw new Error('Wallet signature was not completed.');
const {error}=await sb.from('profiles').update({wallet_address:address}).eq('id',user.id);if(error)throw error;
const addr=card.querySelector('.wallet-address'),txt=card.querySelector('.wallet-text');if(addr)addr.textContent=short(address);if(txt)txt.textContent='Wallet verified and connected to your Buyer profile on BNB Smart Chain.';link.textContent='Wallet Verified ✓';link.style.pointerEvents='none';card.dataset.walletAddress=address;card.dataset.walletSignature=signature;alert('Wallet connected successfully. Your wallet address is now linked to your Buyer account.');}catch(err){link.textContent=old;link.style.pointerEvents='auto';alert(err?.message||'Wallet connection failed.');}})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,300));else setTimeout(init,300);new MutationObserver(()=>init()).observe(document.body,{childList:true,subtree:true});})();