"use strict";
(async function(){
 const root=document.querySelector('#dealApp')||document.querySelector('.room'); if(!root)return;
 const sleep=ms=>new Promise(r=>setTimeout(r,ms)); let sb=null;
 for(let i=0;i<40;i++){sb=window.Web3MarketSupabase?.getClient?.()||window.supabaseClient||window.web3marketSupabase||null;if(sb)break;await sleep(100)}
 if(!sb&&window.supabase?.createClient){try{sb=window.supabase.createClient('https://hzhqlexnhtukfljcvnyd.supabase.co','sb_publishable_lO7uEsiM0T8oeHB75DMxkA_287VZ9eI',{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storageKey:'web3market-auth'}});window.supabaseClient=sb}catch(e){console.error(e)}}
 if(!sb){root.innerHTML='<div class="status">Database connection unavailable. Please refresh the page.</div>';return}
 const {data:{user},error:ue}=await sb.auth.getUser(); if(ue||!user){location.replace('login.html?next='+encodeURIComponent(location.pathname+location.search));return}
 const params=new URLSearchParams(location.search),dealId=params.get('deal')||params.get('id'); if(!dealId){root.innerHTML='<div class="status">Deal not specified.</div>';return}
 const {data:deal,error}=await sb.from('deals').select('*').eq('id',dealId).maybeSingle();
 if(error||!deal){console.error(error);root.innerHTML='<div class="status">Deal information is unavailable.</div>';return}
 const participant=String(deal.buyer_id)===String(user.id)?'buyer':String(deal.seller_id)===String(user.id)?'seller':null;
 if(!participant){root.innerHTML='<div class="status">You are not a participant in this deal.</div>';return}
 const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));
 const money=v=>Number(v||0).toLocaleString(undefined,{maximumFractionDigits:2})+' '+(deal.currency||'USDT');
 document.querySelector('#dealMeta').textContent=`Deal ${deal.id} · ${money(deal.amount)}`; document.querySelector('#dealStatus').textContent=String(deal.status||'pending').replace(/[_-]+/g,' ');
 const details=document.querySelector('#details'); if(details)details.innerHTML=`<p>Amount: <strong>${esc(money(deal.amount))}</strong></p><p>Multisig: <strong>2-of-3</strong></p><p>Signers: Buyer · Seller · Web3Market</p><p>Payment: <strong>${esc(deal.payment_status||'pending')}</strong></p><p>Role: <strong>${participant}</strong></p><p>Platform fee: <strong>${esc(money(deal.platform_fee_amount??deal.platform_fee))}</strong></p>`;
 async function loadAgreement(){const {data,error}=await sb.from('deal_party_agreements').select('party_role,party_id,agreed_at').eq('deal_id',deal.id);if(error){console.error('agreement',error);return null}return data||[]}
 async function loadMessages(){const {data,error}=await sb.from('deal_messages').select('message,created_at,sender_id').eq('deal_id',deal.id).order('created_at',{ascending:true});if(error){console.error(error);return}const box=document.querySelector('#messages');if(!box)return;box.innerHTML=(data||[]).map(m=>`<div class="msg ${String(m.sender_id)===String(user.id)?'mine':''}">${esc(m.message)}<small>${new Date(m.created_at).toLocaleString()}</small></div>`).join('')||'<div class="info">No messages yet.</div>';box.scrollTop=box.scrollHeight}
 async function renderTerms(){const rows=await loadAgreement(),mine=rows.find(x=>x.party_role===participant&&String(x.party_id)===String(user.id)),buyer=rows.find(x=>x.party_role==='buyer')?.agreed_at,seller=rows.find(x=>x.party_role==='seller')?.agreed_at,actions=document.querySelector('#actions');if(!actions)return;actions.innerHTML=`<div class="notice"><strong>Dispute Resolution — Model B</strong><br>Buyer and Seller agree that Web3Market acts as the dispute resolution party. Funds are held by the 2-of-3 multisig, not by Web3Market. ${buyer?'Buyer ✓':'Buyer pending'} · ${seller?'Seller ✓':'Seller pending'}</div><button id="agreeBtn" class="btn primary" ${mine?.agreed_at?'disabled':''}>${mine?.agreed_at?'✓ Agreement Accepted':'I Agree to Deal Terms'}</button><button id="disputeBtn" class="btn" style="background:#fff7ed;color:#9a3412">Open Dispute</button>`;
 const agreeBtn=document.querySelector('#agreeBtn');if(agreeBtn&&!mine?.agreed_at)agreeBtn.onclick=async()=>{agreeBtn.disabled=true;let {data:row}=await sb.from('deal_party_agreements').select('id').eq('deal_id',deal.id).eq('party_role',participant).eq('party_id',user.id).maybeSingle();let error;if(row){({error}=await sb.from('deal_party_agreements').update({agreed_at:new Date().toISOString()}).eq('id',row.id))}else{({error}=await sb.from('deal_party_agreements').insert({deal_id:deal.id,party_role:participant,party_id:user.id,agreed_at:new Date().toISOString()}))}if(error){alert(error.message||'Could not save agreement');agreeBtn.disabled=false;return}await renderTerms()};
 const db=document.querySelector('#disputeBtn');if(db)db.onclick=async()=>{const reason=prompt('Describe the dispute');if(!reason)return;const {error}=await sb.from('deal_disputes').insert({deal_id:deal.id,opened_by:user.id,reason,status:'open'});if(error)alert(error.message||'Could not open dispute');else alert('Dispute opened for Web3Market review.')};}
 await loadMessages();await renderTerms();
 const form=document.querySelector('#chatForm');if(form)form.addEventListener('submit',async e=>{e.preventDefault();const input=document.querySelector('#messageInput'),message=input?.value.trim();if(!message)return;const btn=form.querySelector('button');btn.disabled=true;const {error}=await sb.from('deal_messages').insert({deal_id:deal.id,sender_id:user.id,message});btn.disabled=false;if(error){alert(error.message||'Unable to send message.');return}input.value='';await loadMessages()});
 const channel=sb.channel('deal-messages-'+deal.id).on('postgres_changes',{event:'INSERT',schema:'public',table:'deal_messages',filter:'deal_id=eq.'+deal.id},loadMessages).subscribe();window.addEventListener('beforeunload',()=>sb.removeChannel(channel));
})();
