"use strict";
(function(){
 const page=document.getElementById('page');
 const SUPABASE_URL='https://hzhqlexnhtukfljcvnyd.supabase.co';
 const SUPABASE_KEY='sb_publishable_lO7uEsiM0T8oeHB75DMxkA_287VZ9eI';
 let fallbackClient=null;
 const sb=()=>{const x=window.Web3MarketSupabase?.getClient?.()||window.supabaseClient||window.web3marketSupabase;if(x?.from)return x;if(fallbackClient?.from)return fallbackClient;if(window.supabase?.createClient){try{fallbackClient=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storageKey:'web3market-auth'}});return fallbackClient}catch(e){console.error(e)}}return null};
 const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));
 const money=(v,c='USD')=>{const n=Number(v);return Number.isFinite(n)?new Intl.NumberFormat('en-US',{style:'currency',currency:c||'USD',maximumFractionDigits:0}).format(n):'Price on request'};
 const score=(l,v)=>`<div style="padding:12px;border:1px solid #e6eaf0;border-radius:12px"><strong>${esc(l)}</strong><div style="font-size:24px;font-weight:700;margin-top:4px">${v==null?'—':esc(Math.round(Number(v)))+'/100'}</div></div>`;
 const badge=(ok,l)=>`<span style="display:inline-block;margin:4px 6px 4px 0;padding:5px 9px;border-radius:999px;background:${ok?'#e8f7ee':'#f1f3f5'};color:${ok?'#16733b':'#667085'};font-size:13px">${ok?'✓':'○'} ${l}</span>`;
 async function load(){
  try{
   const id=new URLSearchParams(location.search).get('id');
   if(!id){page.textContent='Project not specified.';return}
   const client=sb(); if(!client){page.innerHTML='Database connection unavailable. <button onclick="location.reload()">Retry</button>';return}
   const {data:p,error}=await client.from('projects').select('*').eq('id',id).maybeSingle();
   if(error)throw error;if(!p){page.textContent='Project not found or unavailable.';return}
   document.title=`${p.title||'Project'} | Web3Market`;
   const results=await Promise.allSettled([
    client.from('web3market_reputation').select('reputation_score,completed_deals,disputed_deals,wallet_verified,ownership_verified,github_verified,domain_verified,identity_verified,business_verified').eq('user_id',p.owner_id).maybeSingle(),
    client.from('project_verification_summary').select('ownership_verified,domain_verified,github_verified,identity_verified,business_verified,verification_score,badges').eq('project_id',p.id).maybeSingle(),
    client.from('project_intelligence').select('overall_score,investment_score,technical_score,security_score,revenue_score,market_score,acquisition_readiness_score,confidence_score,risk_level,ai_summary,strengths,risk_signals,data_gaps,valuation_low,valuation_mid,valuation_high,valuation_method,price_position').eq('project_id',p.id).maybeSingle(),
    client.from('deal_intelligence').select('*').eq('project_id',p.id).maybeSingle(),
    client.auth.getUser()
   ]);
   const val=i=>results[i]?.status==='fulfilled'?results[i].value:{};
   const rep=val(0).data||{},ver=val(1).data||{},intel=val(2).data||null;
   let deal=val(3).data||null;const user=val(4).data?.user||null;
   if(!deal&&user){try{const r=await client.rpc('calculate_deal_score',{p_project_id:p.id});if(!r.error)deal=r.data}catch(e){console.warn('Deal score unavailable',e)}}
   const ts=Number(rep.reputation_score),vs=Number(ver.verification_score);
   const arr=v=>Array.isArray(v)?v.join(' · '):(v||'None recorded.');
   const intelligenceCard=intel?`<div class="card" style="margin-top:24px;border:1px solid #d9e2ec;background:#fff"><div style="display:flex;justify-content:space-between;gap:20px;align-items:flex-start;flex-wrap:wrap"><div><span class="eyebrow">WEB3MARKET INTELLIGENCE</span><h2>AI Due Diligence & AI Valuation</h2><p class="desc">Decision-support analysis based on available marketplace evidence.</p></div><div style="text-align:center;min-width:130px"><small>PROJECT SCORE</small><strong style="display:block;font-size:44px">${esc(Math.round(Number(intel.overall_score)||0))}/100</strong><div>${esc(String(intel.risk_level||'unknown').toUpperCase())} RISK</div></div></div><div class="grid" style="margin-top:18px">${score('Investment',intel.investment_score)}${score('Technical',intel.technical_score)}${score('Security',intel.security_score)}${score('Revenue',intel.revenue_score)}${score('Market',intel.market_score)}${score('Acquisition Readiness',intel.acquisition_readiness_score)}</div><div class="grid" style="margin-top:18px"><div style="padding:16px;border:1px solid #e6eaf0;border-radius:12px"><strong>AI Valuation</strong><div style="font-size:30px;font-weight:700;margin-top:5px">${money(intel.valuation_mid,p.currency)}</div><div class="desc">Fair Value · Range ${money(intel.valuation_low,p.currency)} – ${money(intel.valuation_high,p.currency)}</div><p><strong>Asking:</strong> ${money(p.price,p.currency)} · <strong>${esc(String(intel.price_position||'unknown').replaceAll('_',' ').toUpperCase())}</strong></p></div><div style="padding:16px;border:1px solid #e6eaf0;border-radius:12px"><strong>AI Summary</strong><p class="desc">${esc(intel.ai_summary||'The valuation uses the available project and financial evidence.')}</p><small>Confidence: ${esc(Math.round(Number(intel.confidence_score)||0))}% · ${esc(intel.valuation_method||'Marketplace valuation model')}</small></div></div><div style="margin-top:18px"><strong>Strengths</strong><p class="desc">${esc(arr(intel.strengths))}</p><strong>Risk Signals</strong><p class="desc">${esc(arr(intel.risk_signals))}</p><strong>Data Gaps</strong><p class="desc">${esc(arr(intel.data_gaps))}</p></div><div style="margin-top:16px;display:flex;gap:10px;flex-wrap:wrap"><a class="btn btn-primary" href="ai-due-diligence.html?id=${encodeURIComponent(p.id)}">Open full AI Due Diligence</a><a class="btn btn-ghost" href="#offerForm">Make an offer</a></div><small>Informational marketplace analysis only — not an independent audit, guarantee, investment advice, or financial recommendation.</small></div>`:`<div class="card" style="margin-top:24px"><h2>AI Due Diligence & AI Valuation</h2><p class="desc">Intelligence data is not available for this project yet.</p><a class="btn btn-ghost" href="ai-due-diligence.html?id=${encodeURIComponent(p.id)}">Open AI Due Diligence</a></div>`;
   const dealCard=deal?`<div class="card" style="margin-top:24px"><div style="display:flex;justify-content:space-between;align-items:center;gap:15px;flex-wrap:wrap"><div><h2>Web3Market Deal Score</h2><p class="desc">Attractiveness of the current asking price relative to quality, value, trust and risk.</p></div><strong style="font-size:42px">${esc(deal.deal_score??'—')}/100</strong></div><div class="grid"><div><strong>Project Score</strong><p>${esc(deal.project_score??'—')}/100</p></div><div><strong>Fair Value</strong><p>${money(deal.fair_value??intel?.valuation_mid,p.currency)}</p></div><div><strong>Asking Price</strong><p>${money(deal.asking_price??p.price,p.currency)}</p></div><div><strong>Trust Score</strong><p>${esc(deal.trust_score??'—')}/100</p></div></div><small>Informational marketplace signal only.</small></div>`:`<div class="card" style="margin-top:24px"><h2>Web3Market Deal Score</h2><p class="desc">Sign in to calculate the Deal Score.</p></div>`;
   page.className='';page.innerHTML=`<section style="max-width:1000px;margin:auto;padding:40px 0"><span class="eyebrow">${esc(p.category||'Web3 Project')} · ${esc(p.status||'active')}</span><h1>${esc(p.title||'Untitled Web3 Project')}</h1><p>${esc(p.description||'No description provided.')}</p><div class="hero-actions"><strong style="font-size:28px">${money(p.price,p.currency)}</strong> <a class="btn btn-ghost" href="ai-due-diligence.html?id=${encodeURIComponent(p.id)}">AI Due-Diligence</a></div>${intelligenceCard}<div class="card" style="margin-top:24px"><h2>Trust & Verification</h2><div class="grid"><div><strong>Seller Reputation</strong><p style="font-size:26px">${Number.isFinite(ts)?Math.round(ts)+'/100':'Not rated'}</p></div><div><strong>Project Verification</strong><p style="font-size:26px">${Number.isFinite(vs)?Math.round(vs)+'/100':'Not verified'}</p></div><div><strong>Completed Deals</strong><p>${Number(rep.completed_deals)||0}</p></div><div><strong>Disputes</strong><p>${Number(rep.disputed_deals)||0}</p></div></div><div>${badge(!!rep.wallet_verified,'Wallet Verified')}${badge(!!rep.ownership_verified||!!ver.ownership_verified,'Ownership Verified')}${badge(!!rep.github_verified||!!ver.github_verified,'GitHub Verified')}${badge(!!rep.domain_verified||!!ver.domain_verified,'Domain Verified')}${badge(!!rep.identity_verified||!!ver.identity_verified,'Identity Verified')}${badge(!!rep.business_verified||!!ver.business_verified,'Business Verified')}</div></div>${dealCard}<div class="grid" style="margin-top:30px"><div class="card"><h2>Project overview</h2><p class="desc" style="white-space:pre-wrap">${esc(p.description||'')}</p></div><div class="card"><h2>Make an offer</h2><p class="desc">Submit an offer. Funds are not collected by this form.</p><form id="offerForm"><label>Offer amount<input name="amount" type="number" min="0.01" step="0.01" required></label><label>Message<textarea name="message" maxlength="5000" placeholder="Introduce yourself and your terms"></textarea></label><button class="btn btn-primary" type="submit">Send offer</button><div id="offerStatus" class="status"></div></form></div></div></section>`;
   document.getElementById('offerForm').addEventListener('submit',e=>offer(e,p,sb()));
  }catch(err){console.error('Web3Market project page:',err);page.className='status';page.innerHTML=`Unable to load this project. <button onclick="location.reload()">Retry</button><br><small>${esc(err?.message||'Unknown error')}</small>`}
 }
 async function offer(e,p,client){e.preventDefault();const out=document.getElementById('offerStatus');try{const {data:{user}}=await client.auth.getUser();if(!user){out.textContent='Please sign in before making an offer.';return}if(p.owner_id===user.id){out.textContent='You cannot make an offer on your own project.';return}const fd=new FormData(e.currentTarget),amount=Number(fd.get('amount'));if(!Number.isFinite(amount)||amount<=0){out.textContent='Enter a valid amount.';return}const {data:deal,error}=await client.from('deals').insert({project_id:p.id,buyer_id:user.id,seller_id:p.owner_id,amount,currency:p.currency||'USD',status:'pending'}).select('id').single();if(error)throw error;const message=String(fd.get('message')||'').trim();if(message)await client.from('deal_messages').insert({deal_id:deal.id,sender_id:user.id,message});out.textContent='Offer submitted successfully.';e.currentTarget.reset()}catch(err){console.error(err);out.textContent=err?.message||'Unable to submit offer.'}}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load,{once:true});else load();
})();