"use strict";
(async function(){
 const root=document.querySelector('#scoreApp');
 const id=new URLSearchParams(location.search).get('id');
 const sb=window.Web3MarketSupabase?.getClient?.()||window.supabaseClient||window.web3marketSupabase;
 const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));
 const score=v=>v==null?'—':`${Math.round(Number(v))}/100`;
 const money=v=>v==null||Number(v)<=0?'Not available':new Intl.NumberFormat(undefined,{maximumFractionDigits:0}).format(Number(v));
 const pct=v=>v==null?0:Math.max(0,Math.min(100,Number(v)));
 const arr=v=>Array.isArray(v)?v:[];
 if(!root)return;
 if(!sb){root.innerHTML='<div class="status">Database connection unavailable.</div>';return;}
 if(!id){root.innerHTML='<div class="status">No project selected.</div>';return;}
 try{
  const {data:p,error:pe}=await sb.from('projects').select('*').eq('id',id).maybeSingle();
  if(pe||!p){root.innerHTML='<div class="status">Project not found or unavailable.</div>';return;}
  let {data:intel}=await sb.from('project_intelligence').select('overall_score,investment_score,technical_score,security_score,revenue_score,market_score,acquisition_readiness_score,confidence_score,score_explanation,calculated_at,score_version,ai_summary,risk_level,risk_signals,strengths,data_gaps,valuation_low,valuation_high,valuation_mid,valuation_method,price_position').eq('project_id',id).maybeSingle();
  let generated=false;
  if(!intel){const {data:{user}}=await sb.auth.getUser();if(user){const {data:calculated,error:ce}=await sb.rpc('calculate_project_intelligence',{p_project_id:id});if(!ce&&calculated){intel=Array.isArray(calculated)?calculated[0]:calculated;generated=true;}}}
  if(!intel){root.innerHTML=`<div class="card"><h2>${esc(p.title||'Project')}</h2><div class="status">Project Intelligence is not available yet.</div><p>Sign in as the project owner to generate the first score.</p></div>`;return;}
  const dimensions=[['Investment Score','investment_score','Revenue quality, market traction, technical quality and trust signals contribute to this score.'],['Technical Score','technical_score','GitHub, technology stack, documentation, project URL, blockchain and development stage are considered.'],['Security Score','security_score','Ownership, identity, business and verification signals are considered.'],['Revenue Score','revenue_score','Revenue, profit, revenue sources, revenue status and growth information are considered.'],['Market Score','market_score','Users, customers, visits, sales/volume and stated market opportunity are considered.'],['Acquisition Readiness','acquisition_readiness_score','Measures how complete the project is for an acquisition, including technical, security, financial and transfer readiness.']];
  const explanation=intel.score_explanation&&typeof intel.score_explanation==='object'?intel.score_explanation:{};
  const badge=v=>v==null?'':(Number(v)>=80?'Strong':Number(v)>=60?'Moderate':Number(v)>=40?'Developing':'Limited');
  const riskLabel={low:'Low Risk Signal',medium:'Moderate Risk Signal',high:'High Risk Signal',critical:'Critical Risk Signal',unknown:'Risk Not Yet Determined'}[intel.risk_level]||'Risk Not Yet Determined';
  const positionLabel={undervalued:'Potentially Undervalued',fair_value:'Within Estimated Fair Value',overpriced:'Potentially Overpriced',not_available:'Price Position Not Available'}[intel.price_position]||'Price Position Not Available';
  const strengths=arr(intel.strengths),risks=arr(intel.risk_signals),gaps=arr(intel.data_gaps);
  const reasonText=(items,empty)=>items.length?items.map(x=>`<li>${esc(x)}</li>`).join(''):`<li>${esc(empty)}</li>`;
  const cards=dimensions.map(([label,key,desc])=>{const value=intel[key];return `<div class="card"><div style="display:flex;justify-content:space-between;gap:12px;align-items:center"><h3 style="margin:0">${label}</h3><strong>${score(value)}</strong></div><div class="meter"><span style="width:${pct(value)}%"></span></div><p class="desc">${esc(desc)}</p><p><strong>${esc(badge(value))}</strong></p></div>`;}).join('');
  const asking=p.asking_price??p.price;
  const valuation=(intel.valuation_mid&&Number(intel.valuation_mid)>0)?`<div class="card valuation-card"><span class="eyebrow">AI VALUATION SIGNAL</span><h3>Estimated Fair Value Range</h3><div class="valuation">${money(intel.valuation_low)} – ${money(intel.valuation_high)} ${esc(p.currency_code||p.currency||'')}</div><p><strong>Midpoint:</strong> ${money(intel.valuation_mid)} ${esc(p.currency_code||p.currency||'')}</p><p><span class="intel-pill">${esc(positionLabel)}</span></p>${asking!=null?`<p><strong>Asking Price:</strong> ${money(asking)} ${esc(p.currency_code||p.currency||'')}</p>`:''}<p class="valuation-note">Method: ${esc(intel.valuation_method||'Deterministic valuation model using available financial signals.')}</p><p class="muted">This is an automated estimate, not a professional appraisal or investment advice.</p></div>`:'<div class="card"><h3>Valuation</h3><p>Not enough financial data is available to produce a reliable valuation range. Web3Market will not invent revenue or profit figures.</p></div>';
  document.title=`${p.title||'Project'} Score | Web3Market`;
  root.innerHTML=`<div class="card" style="text-align:center"><span class="eyebrow">PROJECT INTELLIGENCE ${esc(intel.score_version||explanation.version||'v3')}</span><h2>${esc(p.title||'Project')}</h2><div style="font-size:56px;font-weight:800;line-height:1.1;margin:18px 0">${score(intel.overall_score)}</div><p><strong>${esc(badge(intel.overall_score))}</strong> overall project signal</p><p class="desc">This is an informational model based on available project data. It is not financial advice, an audit, or a guarantee of project quality.</p></div>${valuation}<div class="card" style="margin-top:14px"><h3>AI Project Summary</h3><p>${esc(intel.ai_summary||'A project summary will appear after intelligence is calculated.')}</p><p><strong>${esc(riskLabel)}</strong></p></div><div class="score-grid">${cards}</div><div class="card" style="margin-top:14px"><h3>Why this score?</h3><p>The model evaluates completeness and trust signals across the project profile. Missing information is not treated as proof of a problem; it reduces confidence and can limit the score.</p></div><div class="score-grid"><div class="card"><h3>Strengths</h3><ul class="risk-list">${reasonText(strengths,'No specific strengths were identified yet.')}</ul></div><div class="card"><h3>Risk Signals</h3><ul class="risk-list">${reasonText(risks,'No specific risk signals were identified by this model.')}</ul></div><div class="card"><h3>Data Gaps</h3><ul class="risk-list">${reasonText(gaps,'No major data gaps were identified.')}</ul></div></div><div class="card" style="margin-top:14px"><h3>Confidence & Methodology</h3><p><strong>Confidence:</strong> ${score(intel.confidence_score)}</p><p><strong>Data points:</strong> ${Number(explanation.data_points||0)}</p><p><strong>Model:</strong> ${esc(explanation.method||'Deterministic project intelligence model')}</p><p><strong>Version:</strong> ${esc(intel.score_version||explanation.version||'v3')}</p><p><strong>Last calculated:</strong> ${intel.calculated_at?esc(new Date(intel.calculated_at).toLocaleString()):'—'}</p>${generated?'<p><strong>✓ Score generated from the current project data.</strong></p>':''}</div>`;
 }catch(err){console.error('Project Score error:',err);root.innerHTML='<div class="status">Unable to load project intelligence.</div>';}
})();