"use strict";
(function(){
const BSC="0x38";
const FN="https://hzhqlexnhtukfljcvnyd.supabase.co/functions/v1/wallet-verify-v2";
const providers=[],seen=new Set();
const sb=()=>window.Web3MarketSupabase?.getClient?.()||window.Web3MarketSupabase?.client||window.supabaseClient||window.web3marketSupabase;
const short=a=>a.slice(0,8)+"…"+a.slice(-6);
const esc=v=>String(v??"").replace(/[&<>\"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]));
const walletParam=()=>new URLSearchParams(location.search).get("wm_wallet");
function add(p,i={}){if(p&&typeof p.request==="function"&&!seen.has(p)){seen.add(p);providers.push({p,i})}}
function discover(){try{if(window.safepalProvider)add(window.safepalProvider,{name:"SafePal",rdns:"com.safepal.wallet"});const e=window.ethereum;if(e?.providers?.length)e.providers.forEach(p=>add(p,p.info||{}));else if(e)add(e,e.info||{});window.dispatchEvent(new Event("eip6963:requestProvider"))}catch(_) {}}
window.addEventListener("eip6963:announceProvider",e=>{const d=e.detail||{};add(d.provider,d.info||{})});
function nameOf(x){const s=String(x.i?.name||x.i?.rdns||x.p?.name||"").toLowerCase();if(s.includes("safepal"))return"SafePal";if(s.includes("metamask"))return"MetaMask";if(s.includes("trust"))return"Trust Wallet";if(s.includes("coinbase"))return"Coinbase Wallet";if(s.includes("okx"))return"OKX Wallet";if(s.includes("binance"))return"Binance Wallet";if(s.includes("rabby"))return"Rabby Wallet";if(s.includes("phantom"))return"Phantom";if(s.includes("zerion"))return"Zerion";return x.i?.name||x.p?.name||"Web3 Wallet"}
function close(){const m=document.getElementById("walletModal");if(m)m.hidden=true}
function notice(t){const n=document.getElementById("walletNotice");if(n)n.textContent=t}
function openWalletApp(name){const page=encodeURIComponent(location.origin+location.pathname+"?wm_wallet="+encodeURIComponent(name));const links={"MetaMask":`https://metamask.app.link/dapp/${location.host}${location.pathname}?wm_wallet=${encodeURIComponent(name)}`,"Trust Wallet":`https://link.trustwallet.com/open_url?url=${page}`,"Coinbase Wallet":`https://go.cb-w.com/dapp?cb_url=${page}`,"OKX Wallet":`okx://wallet/dapp/url?dappUrl=${page}`,"Binance Wallet":`https://www.binance.com/en/web3wallet?url=${page}`};if(name==="SafePal"){notice("SafePal is ready. Open SafePal → Explore/DApp Browser → open web3market.xyz. The wallet will inject its provider and the FREE ownership signature will appear automatically.");return}const u=links[name];if(u)location.href=u;else notice(`Open ${name} and use its built-in DApp browser to visit Web3Market.`)}
async function connect(p,name){const btn=document.getElementById("connectSellerWallet");try{close();if(btn){btn.disabled=true;btn.textContent="Connecting…"}notice(`Connecting ${name}…`);const a=(await p.request({method:"eth_requestAccounts"}))?.[0];if(!a)throw Error("No wallet account was returned.");let chain=await p.request({method:"eth_chainId"});if(chain!==BSC){try{await p.request({method:"wallet_switchEthereumChain",params:[{chainId:BSC}]})}catch(e){if(e?.code===4902)await p.request({method:"wallet_addEthereumChain",params:[{chainId:BSC,chainName:"BNB Smart Chain",nativeCurrency:{name:"BNB",symbol:"BNB",decimals:18},rpcUrls:["https://bsc-dataseed.binance.org/"],blockExplorerUrls:["https://bscscan.com/"]}]});else throw e}chain=await p.request({method:"eth_chainId"})}if(chain!==BSC)throw Error("Please switch the wallet to BNB Smart Chain.");const c=sb();if(!c?.auth)throw Error("Web3Market authentication is unavailable.");const s=await c.auth.getSession();const token=s.data?.session?.access_token;if(!token)throw Error("Please sign in again.");notice("Preparing a secure one-time ownership challenge…");let r=await fetch(FN,{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+token},body:JSON.stringify({action:"challenge",address:a})});let d=await r.json().catch(()=>({}));if(!r.ok||!d.ok||!d.message||!d.nonce)throw Error(d.error||"Unable to start wallet verification.");notice("Confirm the FREE ownership signature in your wallet…");const sig=await p.request({method:"personal_sign",params:[d.message,a]});if(!sig)throw Error("Signature was cancelled.");notice("Verifying and saving your wallet…");r=await fetch(FN,{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+token},body:JSON.stringify({action:"verify",address:a,nonce:d.nonce,signature:sig})});d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw Error(d.error||"Wallet verification failed.");const ae=document.getElementById("sellerWalletAddress"),se=document.getElementById("sellerWalletStatus");if(ae)ae.textContent=short(a);if(se)se.textContent="Connected & verified ✓";notice("Wallet verified and saved to your seller profile.");if(btn){btn.disabled=false;btn.textContent="Wallet Connected ✓";btn.classList.add("connected")}}catch(e){console.warn("Seller wallet:",e);notice(e?.message||"Wallet connection failed.");if(btn){btn.disabled=false;btn.textContent="Connect Wallet"}}}
function open(){discover();setTimeout(()=>{const m=document.getElementById("walletModal"),list=document.getElementById("walletList");if(!m||!list)return;list.innerHTML="";const wanted=["MetaMask","Trust Wallet","SafePal","Coinbase Wallet","OKX Wallet","Binance Wallet","Rabby Wallet","Phantom","Zerion"],rows=[],used=new Set();providers.forEach(x=>{const n=nameOf(x);if(!used.has(n)){used.add(n);rows.push({n,x})}});wanted.forEach(n=>{if(!used.has(n)){used.add(n);rows.push({n,x:null})}});rows.forEach(row=>{const b=document.createElement("button");b.type="button";b.className="wallet-option";b.style.cursor="pointer";const detected=!!row.x;b.innerHTML=`<span class="wallet-icon">◈</span><span><strong>${esc(row.n)}</strong><small>${detected?"Detected on this device":row.n==="SafePal"?"Open SafePal DApp browser":"Open wallet app / browser"}</small></span><span class="wallet-arrow">›</span>`;b.addEventListener("click",()=>row.x?connect(row.x.p,row.n):openWalletApp(row.n));list.appendChild(b)});m.hidden=false},100)}
function bind(){const b=document.getElementById("connectSellerWallet");if(b&&!b.dataset.bound){b.dataset.bound="1";b.addEventListener("click",open)}const c=document.getElementById("walletModalClose");if(c&&!c.dataset.bound){c.dataset.bound="1";c.addEventListener("click",close)}}
async function auto(){const n=walletParam();if(!n)return;discover();for(let i=0;i<16;i++){await new Promise(r=>setTimeout(r,250));const x=providers.find(v=>nameOf(v)===n);if(x){await connect(x.p,n);history.replaceState({},"",location.pathname);return}}notice(`${n} selected. Open Web3Market inside the wallet's DApp browser; the FREE ownership signature will appear there.`)}
discover();if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>{bind();auto()},{once:true});else{bind();auto()}
})();