"use strict";
(function(){
const BSC="0x38",FN="https://hzhqlexnhtukfljcvnyd.supabase.co/functions/v1/wallet-verify-handoff";
const providers=[],seen=new Set(),sb=()=>window.Web3MarketSupabase?.getClient?.()||window.Web3MarketSupabase?.client||window.supabaseClient||window.web3marketSupabase,short=a=>a.slice(0,8)+"…"+a.slice(-6),esc=v=>String(v??"").replace(/[&<>\"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]));
const walletParam=()=>new URLSearchParams(location.search).get("wm_wallet"),handoffParam=()=>new URLSearchParams(location.search).get("wm_handoff")||new URLSearchParams(location.hash.replace(/^#/,'')).get("wm_handoff");
function add(p,i={}){if(p&&typeof p.request==="function"&&!seen.has(p)){seen.add(p);providers.push({p,i})}}
function discover(){try{if(window.safepalProvider)add(window.safepalProvider,{name:"SafePal",rdns:"com.safepal.wallet"});const tw=window.trustwallet?.ethereum||window.trustwallet;if(tw?.request)add(tw,{name:"Trust Wallet",rdns:"com.trustwallet.app"});const e=window.ethereum;if(e?.providers?.length)e.providers.forEach(p=>add(p,p.info||{}));else if(e)add(e,e.info||{});window.dispatchEvent(new Event("eip6963:requestProvider"))}catch(_) {}}
window.addEventListener("eip6963:announceProvider",e=>{const d=e.detail||{};add(d.provider,d.info||{})});window.addEventListener("trustwallet#initialized",()=>discover(),{once:false});
function nameOf(x){const s=String(x.i?.name||x.i?.rdns||x.p?.name||"").toLowerCase();if(s.includes("safepal"))return"SafePal";if(s.includes("metamask"))return"MetaMask";if(s.includes("trust"))return"Trust Wallet";if(s.includes("coinbase"))return"Coinbase Wallet";if(s.includes("okx"))return"OKX Wallet";if(s.includes("binance"))return"Binance Wallet";if(s.includes("rabby"))return"Rabby Wallet";if(s.includes("phantom"))return"Phantom";if(s.includes("zerion"))return"Zerion";return x.i?.name||x.p?.name||"Web3 Wallet"}
function close(){const m=document.getElementById("walletModal");if(m)m.hidden=true}function notice(t){const n=document.getElementById("walletNotice");if(n)n.textContent=t}
async function createHandoff(name){const c=sb();if(!c?.auth)throw Error("Web3Market authentication is unavailable. Refresh and sign in again.");const s=await c.auth.getSession(),token=s.data?.session?.access_token;if(!token)throw Error("Please sign in again before connecting your wallet.");const r=await fetch(FN,{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+token},body:JSON.stringify({action:"handoff",wallet_type:name})}),d=await r.json().catch(()=>({}));if(!r.ok||!d.ok||!d.handoff)throw Error(d.error||"Unable to start secure wallet handoff.");return d.handoff}
function openWalletUrl(name,h){const page=location.origin+location.pathname+"?wm_wallet="+encodeURIComponent(name)+"&wm_handoff="+encodeURIComponent(h),u=encodeURIComponent(page),links={"MetaMask":`https://metamask.app.link/dapp/${location.host}${location.pathname}?wm_wallet=${encodeURIComponent(name)}&wm_handoff=${encodeURIComponent(h)}`,"Trust Wallet":`https://link.trustwallet.com/open_url?url=${u}`,"Coinbase Wallet":`https://go.cb-w.com/dapp?cb_url=${u}`,"OKX Wallet":`okx://wallet/dapp/url?dappUrl=${u}`,"Binance Wallet":`https://www.binance.com/en/web3wallet?url=${u}`};return links[name]||null}
async function openWalletApp(name){try{const h=await createHandoff(name);if(name==="SafePal"){sessionStorage.setItem("wm_handoff",h);notice("Secure handoff ready. Open SafePal → Explore/DApp and open Web3Market within 2 minutes; if the handoff URL is not preserved, return here and start Connect Wallet again.");return}const u=openWalletUrl(name,h);if(u){notice(`Opening ${name}…`);location.href=u}else notice(`Open ${name} and use its built-in DApp browser to visit Web3Market.`)}catch(e){notice(e?.message||"Unable to open wallet.")}}
async function connect(p,name,h){const btn=document.getElementById("connectSellerWallet");try{close();if(btn){btn.disabled=true;btn.textContent="Connecting…"}notice(`Connecting ${name}…`);const a=(await p.request({method:"eth_requestAccounts"}))?.[0];if(!a)throw Error("No wallet account was returned.");let chain=await p.request({method:"eth_chainId"});if(chain!==BSC){try{await p.request({method:"wallet_switchEthereumChain",params:[{chainId:BSC}]})}catch(e){if(e?.code===4902)await p.request({method:"wallet_addEthereumChain",params:[{chainId:BSC,chainName:"BNB Smart Chain",nativeCurrency:{name:"BNB",symbol:"BNB",decimals:18},rpcUrls:["https://bsc-dataseed.binance.org/"],blockExplorerUrls:["https://bscscan.com/"]}]});else throw e}chain=await p.request({method:"eth_chainId"})}if(chain!==BSC)throw Error("Please switch the wallet to BNB Smart Chain.");const handoff=h||handoffParam()||sessionStorage.getItem("wm_handoff");if(!handoff)throw Error("Secure wallet handoff is missing or expired. Start Connect Wallet again.");let r=await fetch(FN,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"challenge",handoff,address:a})}),d=await r.json().catch(()=>({}));if(!r.ok||!d.ok||!d.message||!d.nonce)throw Error(d.error||"Unable to start wallet verification.");notice("Confirm the FREE ownership signature in your wallet…");const sig=await p.request({method:"personal_sign",params:[d.message,a]});if(!sig)throw Error("Signature was cancelled.");notice("Verifying and saving your wallet…");r=await fetch(FN,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"verify",handoff,address:a,nonce:d.nonce,signature:sig})});d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw Error(d.error||"Wallet verification failed.");sessionStorage.removeItem("wm_handoff");history.replaceState({},"",location.pathname);const ae=document.getElementById("sellerWalletAddress"),se=document.getElementById("sellerWalletStatus");if(ae)ae.textContent=short(a);if(se)se.textContent="Connected & verified ✓";notice("Wallet verified and saved to your seller profile.");if(btn){btn.disabled=false;btn.textContent="Wallet Connected ✓";btn.classList.add("connected")}}catch(e){console.warn("Seller wallet:",e);notice(e?.message||"Wallet connection failed.");if(btn){btn.disabled=false;btn.textContent="Connect Wallet"}}}
function open(){discover();setTimeout(()=>{const m=document.getElementById("walletModal"),list=document.getElementById("walletList");if(!m||!list)return;list.innerHTML="";const wanted=["MetaMask","Trust Wallet","SafePal","Coinbase Wallet","OKX Wallet","Binance Wallet","Rabby Wallet","Phantom","Zerion"],rows=[],used=new Set();providers.forEach(x=>{const n=nameOf(x);if(!used.has(n)){used.add(n);rows.push({n,x})}});wanted.forEach(n=>{if(!used.has(n)){used.add(n);rows.push({n,x:null})}});rows.forEach(row=>{const b=document.createElement("button");b.type="button";b.className="wallet-option";b.style.cursor="pointer";const detected=!!row.x;b.innerHTML=`<span class="wallet-icon">◈</span><span><strong>${esc(row.n)}</strong><small>${detected?"Detected on this device":row.n==="SafePal"?"Open SafePal DApp browser":"Open wallet app / browser"}</small></span><span class="wallet-arrow">›</span>`;b.addEventListener("click",()=>row.x?createHandoff(row.n).then(h=>connect(row.x.p,row.n,h)).catch(e=>notice(e?.message||"Unable to start wallet connection.")):openWalletApp(row.n));list.appendChild(b)});m.hidden=false},100)}
function bind(){const b=document.getElementById("connectSellerWallet");if(b&&!b.dataset.bound){b.dataset.bound="1";b.addEventListener("click",open)}const c=document.getElementById("walletModalClose");if(c&&!c.dataset.bound){c.dataset.bound="1";c.addEventListener("click",close)}}
async function auto(){const n=walletParam(),h=handoffParam()||sessionStorage.getItem("wm_handoff");if(!n&&!h)return;discover();for(let i=0;i<20;i++){await new Promise(r=>setTimeout(r,250));discover();const x=providers.find(v=>nameOf(v)===n);if(x){await connect(x.p,n,h||"");return}}if(n)notice(`${n} selected. Open Web3Market inside the wallet's DApp browser; the FREE ownership signature will appear there.`)}
discover();if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>{bind();auto()},{once:true});else{bind();auto()}
})();