/* Web3Market - Unified Supabase Client + Homepage UI */
"use strict";
(function(){
const SUPABASE_URL="https://hzhqlexnhtukfljcvnyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY="sb_publishable_lO7uEsiM0T8oeHB75DMxkA_287VZ9eI";
const STORAGE_KEY="web3market-auth";let client=null;
function initialize(){if(client)return client;if(!window.supabase||typeof window.supabase.createClient!=="function")return null;try{client=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storageKey:STORAGE_KEY}});window.Web3MarketSupabase={client:client,supabase:client,getClient:()=>client,initialize:initialize,getSession:getSession,getUser:getUser,isInitialized:()=>!!client};window.web3marketSupabase=client;window.supabaseClient=client;return client}catch(e){console.error("Web3Market Supabase:",e);return null}}
function getClient(){return client||initialize()}async function getSession(){const s=getClient();if(!s)return null;try{return (await s.auth.getSession()).data?.session||null}catch(e){return null}}async function getUser(){const s=getClient();if(!s)return null;try{return (await s.auth.getUser()).data?.user||null}catch(e){return null}}
function addStyle(){if(document.getElementById("web3market-ticker-style"))return;const s=document.createElement("style");s.id="web3market-ticker-style";s.textContent="#web3market-news-ticker,#web3market-price-ticker{display:block;width:100%;overflow:hidden;border-radius:10px;margin:4px 0 8px;height:34px;line-height:34px;white-space:nowrap;box-shadow:0 4px 14px rgba(20,24,32,.08)}#web3market-news-ticker{background:#141820;color:#d8dde6}#web3market-news-ticker .wm-track{display:inline-flex;width:max-content;animation:wmTicker 42s linear infinite}#web3market-news-ticker a{color:#d8dde6;text-decoration:none;font-size:11px;font-weight:700;padding:0 18px}#web3market-news-ticker b{color:#635bff;padding:0 4px}#web3market-price-ticker{background:#fff;border:1px solid #e3e6eb;color:#202631}#web3market-price-ticker .wm-price-track{display:inline-flex;gap:28px;align-items:center;padding:0 18px;min-width:100%;justify-content:center}#web3market-price-ticker .coin{font-size:11px;font-weight:850}.coin span{margin-left:5px;font-weight:750}.up{color:#168253!important}.down{color:#c13c3c!important}.flat{color:#737b88!important}.wm-volume-counter{background:#fff;border:1px solid #e3e6eb;border-radius:16px;padding:17px 18px;display:flex;align-items:center;gap:13px;box-shadow:0 7px 20px rgba(20,24,32,.04);min-width:0}.wm-volume-counter .wm-volume-icon{width:42px;height:42px;border-radius:12px;background:#e9f7f0;color:#168253;display:grid;place-items:center;font-weight:950;font-size:17px;flex:0 0 auto}.wm-volume-counter strong{display:block;font-size:20px;line-height:1.05}.wm-volume-counter span{display:block;margin-top:5px;color:#737b88;font-size:10px;font-weight:800}.wm-volume-counter small{display:block;color:#8a919c;font-size:9px;margin-top:3px}@keyframes wmTicker{from{transform:translateX(0)}to{transform:translateX(-50%)}}@media(max-width:950px){.wm-volume-counter strong{font-size:19px}}@media(max-width:620px){#web3market-news-ticker,#web3market-price-ticker{height:31px;line-height:31px}#web3market-news-ticker a{font-size:10px;padding:0 12px}#web3market-price-ticker .wm-price-track{gap:18px;justify-content:flex-start}.wm-volume-counter{padding:14px 12px}.wm-volume-counter .wm-volume-icon{width:36px;height:36px}.wm-volume-counter strong{font-size:17px}}@media(prefers-reduced-motion:reduce){#web3market-news-ticker .wm-track{animation:none}}";document.head.appendChild(s)}
function installHomepageUI(){const counters=document.querySelector(".projectCounters");if(!counters)return false;const grid=counters.querySelector(".counterGrid")||counters.querySelector(".wrap");if(!grid)return false;["Listed","Under AI Review","Pending Execution","Sold"].forEach((x,i)=>{const el=document.querySelectorAll(".projectCounters .counter span")[i];if(el)el.textContent=x});addStyle();
if(!document.getElementById("web3market-news-ticker")){const items=[["Metaplanet agrees to acquire 96% of Super League in a 2,100 BTC and cash deal","https://www.theblock.co/news/deals","The Block · Aug 24, 2026"],["IREN delivers first AI cloud deployment to Microsoft under a reported $9.7B deal","https://www.theblock.co/news/deals","The Block · Aug 24, 2026"],["HIVE signs a five-year $350M AI cloud contract","https://www.theblock.co/news/deals","The Block · Aug 24, 2026"],["Vangrid raises $9M to build a spatial-data network for physical AI","https://www.theblock.co/news/deals","The Block · Aug 24, 2026"],["July crypto M&A activity reached 19 announced acquisitions","https://www.thetie.io/insights/july-2026-crypto-funding-brief","The Tie · Aug 2026"]];const t=document.createElement("div");t.id="web3market-news-ticker";t.setAttribute("aria-label","Latest market news");const tr=document.createElement("div");tr.className="wm-track";items.concat(items).forEach(i=>{const a=document.createElement("a");a.href=i[1];a.target="_blank";a.rel="noopener noreferrer";a.textContent=i[0]+"  |  Source: "+i[2];tr.appendChild(a);const b=document.createElement("b");b.textContent="•";tr.appendChild(b)});t.appendChild(tr);counters.parentNode.insertBefore(t,counters.nextSibling)}
installPriceTicker(counters);installVolumeCounter(grid);return true}
function installPriceTicker(c){let t=document.getElementById("web3market-price-ticker");if(!t){t=document.createElement("div");t.id="web3market-price-ticker";t.setAttribute("aria-label","Live cryptocurrency prices");t.innerHTML='<div class="wm-price-track"><span class="coin" data-symbol="BNB">BNB <span>Loading...</span></span><span class="coin" data-symbol="ETH">ETH <span>Loading...</span></span><span class="coin" data-symbol="SOL">SOL <span>Loading...</span></span></div>';c.parentNode.insertBefore(t,c.nextSibling.nextSibling)}updatePrices(t);if(!t.dataset.timer){t.dataset.timer="1";setInterval(()=>updatePrices(t),30000)}}
async function updatePrices(t){try{const r=await fetch("https://api.coingecko.com/api/v3/simple/price?ids=binancecoin,ethereum,solana&vs_currencies=usd&include_24hr_change=true",{cache:"no-store"});if(!r.ok)throw Error(r.status);const d=await r.json(),m={BNB:d.binancecoin,ETH:d.ethereum,SOL:d.solana};Object.keys(m).forEach(x=>{const e=t.querySelector('[data-symbol="'+x+'"] span'),v=m[x];if(!e||!v)return;const p=Number(v.usd),ch=Number(v.usd_24h_change||0);e.textContent="$"+p.toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:6})+" "+(ch>0?"▲ ":ch<0?"▼ ":"• ")+Math.abs(ch).toFixed(2)+"%";e.className=ch>0?"up":ch<0?"down":"flat"})}catch(e){console.warn("Crypto price ticker:",e)}}
function installVolumeCounter(grid){let t=document.getElementById("web3market-volume-counter");if(!t){t=document.createElement("div");t.id="web3market-volume-counter";t.className="wm-volume-counter counter";t.setAttribute("aria-label","Total completed transaction volume");t.innerHTML='<div class="wm-volume-icon">$</div><div><strong class="volume-value">$0.00</strong><span>Total Transaction Volume</span><small>Completed transactions only</small></div>';grid.appendChild(t);grid.style.gridTemplateColumns="repeat(5,minmax(0,1fr))"}updateVolumeCounter(t);if(!t.dataset.timer){t.dataset.timer="1";setInterval(()=>updateVolumeCounter(t),30000)}}
async function updateVolumeCounter(t){const v=t.querySelector(".volume-value");if(!v)return;try{const s=getClient();if(!s)throw Error("Supabase unavailable");const r=await s.from("market_stats").select("total_transaction_volume").eq("id",true).maybeSingle();if(r.error)throw r.error;const n=Number(r.data?.total_transaction_volume||0);v.textContent="$"+n.toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2})}catch(e){console.warn("Transaction volume counter:",e);v.textContent="$0.00"}}
function installDeveloperContact(){if(!document.querySelector(".projectCounters")||document.getElementById("web3market-developer-contact"))return;const footer=document.createElement("div");footer.id="web3market-developer-contact";footer.innerHTML='<strong>FOR DEVELOPER CONTACT: @Web3j_Global</strong>';footer.style.cssText="width:100%;text-align:center;background:#141820;color:#fff;padding:24px 16px;font-size:18px;font-weight:900;letter-spacing:.2px;box-sizing:border-box";document.body.appendChild(footer)}
function boot(){initialize();if(installHomepageUI()){}installDeveloperContact();setTimeout(installDeveloperContact,800);let n=0;const timer=setInterval(()=>{n++;if(installHomepageUI()||n>30)clearInterval(timer);installDeveloperContact()},250)}if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();window.addEventListener("load",()=>{installHomepageUI();installDeveloperContact()})
})();