"use strict";
(function(){
  const $=s=>document.querySelector(s),grid=$("#projectGrid"),status=$("#status");
  let all=[];
  const client=()=>window.Web3MarketSupabase?.getClient?.()||window.supabaseClient||window.web3marketSupabase||null;
  const esc=v=>String(v??"").replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));
  const money=(v,c)=>v==null||v===''?'Price on request':new Intl.NumberFormat('en-US',{style:'currency',currency:c||'USD',maximumFractionDigits:0}).format(Number(v));
  function card(p){return `<article class="card"><div class="card-head"><div class="logo">W3</div><div><h2>${esc(p.title)}</h2><span class="tag">${esc(p.category||'Web3 Project')}</span></div></div><p class="desc">${esc(p.description||'No description provided.')}</p><div class="stats"><div class="stat"><small>Status</small><strong>${esc(p.status)}</strong></div><div class="stat"><small>Currency</small><strong>${esc(p.currency||'USD')}</strong></div></div><div class="card-foot"><span class="price">${money(p.price,p.currency)}</span><a class="btn btn-secondary" style="min-height:36px;padding:0 12px" href="project.html?id=${encodeURIComponent(p.id)}">View</a></div></article>`}
  function render(){const q=$("#search").value.trim().toLowerCase(),cat=$("#category").value,type=$("#saleType").value,sort=$("#sort").value;let rows=all.filter(p=>(!q||[p.title,p.description,p.category].some(x=>String(x||'').toLowerCase().includes(q)))&&(!cat||p.category===cat));rows.sort((a,b)=>sort==='price_low'?Number(a.price??Infinity)-Number(b.price??Infinity):sort==='price_high'?Number(b.price??0)-Number(a.price??0):new Date(b.created_at)-new Date(a.created_at));grid.innerHTML=rows.length?rows.map(card).join(''):'<div class="empty">No projects match your filters yet.</div>';status.textContent=`Showing ${rows.length} project${rows.length===1?'':'s'}`}
  async function load(){const sb=client();if(!sb){status.textContent='Marketplace connection is unavailable.';return}const {data,error}=await sb.from('projects').select('id,owner_id,title,description,category,price,currency,status,created_at').eq('status','active').order('created_at',{ascending:false});if(error){console.error(error);status.textContent='Unable to load projects right now.';return}all=data||[];$("#projectCount").textContent=all.length;$("#verifiedCount").textContent='—';$("#categoryCount").textContent=new Set(all.map(p=>p.category).filter(Boolean)).size;render()}
  ['search','category','saleType','sort'].forEach(id=>{const el=$("#"+id);if(el)el.addEventListener('input',render)});
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load,{once:true});else load();
})();
