"use strict";
(function(){
  const $=s=>document.querySelector(s), grid=$("#projectGrid"), status=$("#status");
  let all=[];
  const client=()=>window.Web3MarketSupabase?.getClient?.()||window.supabaseClient||window.web3marketSupabase||null;
  const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));
  const money=(v,c)=>v===null||v===undefined||v===''?'Price on request':new Intl.NumberFormat('en-US',{style:'currency',currency:c||'USD',maximumFractionDigits:0}).format(Number(v));
  function card(p){const logo=p.logo_url?`<img class="logo" src="${esc(p.logo_url)}" alt="">`:`<div class="logo">W3</div>`;return `<article class="card"><div class="card-head">${logo}<div><h2>${esc(p.title)}</h2><span class="tag">${esc(p.category)}</span>${p.verification_status==='verified'?'<span class="tag" style="margin-left:5px;color:#34d399;border-color:#255a49">✓ Verified</span>':''}</div></div><p class="desc">${esc(p.short_description)}</p><div class="stats"><div class="stat"><small>Monthly revenue</small><strong>${money(p.monthly_revenue,p.price_currency)}</strong></div><div class="stat"><small>Users</small><strong>${p.users_count==null?'—':Number(p.users_count).toLocaleString()}</strong></div></div><div class="card-foot"><span class="price">${money(p.asking_price,p.price_currency)}</span><span class="score">Score ${p.score}/100</span><a class="btn btn-secondary" style="min-height:36px;padding:0 12px" href="project.html?id=${encodeURIComponent(p.id)}">View</a></div></article>`}
  function render(){const q=$("#search").value.trim().toLowerCase(),cat=$("#category").value,type=$("#saleType").value,sort=$("#sort").value;let rows=all.filter(p=>(!q||[p.title,p.short_description,p.category,p.blockchain].some(x=>String(x||'').toLowerCase().includes(q)))&&(!cat||p.category===cat)&&(!type||p.sale_type===type));rows.sort((a,b)=>sort==='price_low'?Number(a.asking_price||Infinity)-Number(b.asking_price||Infinity):sort==='price_high'?Number(b.asking_price||0)-Number(a.asking_price||0):sort==='score'?Number(b.score)-Number(a.score):new Date(b.created_at)-new Date(a.created_at));grid.innerHTML=rows.length?rows.map(card).join(''):'<div class="empty">No projects match your filters yet.</div>';status.textContent=`Showing ${rows.length} project${rows.length===1?'':'s'}`}
  async function load(){const sb=client();if(!sb){status.textContent='Marketplace connection is unavailable.';return}const {data,error}=await sb.from('marketplace_projects').select('*').in('status',['published','under_offer','sold']).order('featured',{ascending:false}).order('created_at',{ascending:false});if(error){console.error(error);status.textContent='Unable to load projects right now.';return}all=data||[];$("#projectCount").textContent=all.length;$("#verifiedCount").textContent=all.filter(p=>p.verification_status==='verified').length;$("#categoryCount").textContent=new Set(all.map(p=>p.category)).size;render()}
  ['search','category','saleType','sort'].forEach(id=>$("#"+id).addEventListener('input',render));
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load,{once:true});else load();
})();
