name: W3M Permission Test

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/w3m-permission-test.yml"

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "permission test"
